### ISSUE TITLE
REDI should auto-resume in the event of a network timeout

### ISSUE THREAD

**Issue by nrejack** [ctsit/redi#108]
REDI already has an existing feature to resume a previously terminated run. In the event of a network timeout, RED-I can be restarted manually. To complete runs more quickly and without human intervention, RED-I should be able to attempt to recover from a network timeout by automatically resuming, after a user-defined sleep time.

**Comment by nrejack** [comment]
Example error message in log:
2015-01-07 19:34:15,849 - DEBUG - redi.utils.redcapClient - HTTPSConnectionPool(host='www.hcvtargetrc.org', port=443): Max retries exceeded with url: /api/ (Caused by <class 'socket.error'>: [Errno 110] Connection timed out)

**Comment by indera** [comment]
Ruchi is getting the error

redi.utils.redcapClient - ('Connection aborted.', BadStatusLine("''",))

if she  tries to stop the vagrant box during the data transfer.

So it looks like we need a different approach in order to reproduce the "max retries exceeded" error.


=== Relevant documentation to timeouts from the requests library used by PyCap used by our redcapClient.send_data_to_redcap() function:

http://docs.python-requests.org/en/latest/user/advanced/#timeouts
